/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedWellnessRouteImport } from './routes/_authenticated/wellness'
import { Route as AuthenticatedWaterRouteImport } from './routes/_authenticated/water'
import { Route as AuthenticatedRecipeRouteImport } from './routes/_authenticated/recipe'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMealsRouteImport } from './routes/_authenticated/meals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWellnessRoute = AuthenticatedWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaterRoute = AuthenticatedWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipeRoute = AuthenticatedRecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMealsRoute = AuthenticatedMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/recipe': typeof AuthenticatedRecipeRoute
  '/water': typeof AuthenticatedWaterRoute
  '/wellness': typeof AuthenticatedWellnessRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/recipe': typeof AuthenticatedRecipeRoute
  '/water': typeof AuthenticatedWaterRoute
  '/wellness': typeof AuthenticatedWellnessRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meals': typeof AuthenticatedMealsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/recipe': typeof AuthenticatedRecipeRoute
  '/_authenticated/water': typeof AuthenticatedWaterRoute
  '/_authenticated/wellness': typeof AuthenticatedWellnessRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/meals'
    | '/onboarding'
    | '/plan'
    | '/recipe'
    | '/water'
    | '/wellness'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/meals'
    | '/onboarding'
    | '/plan'
    | '/recipe'
    | '/water'
    | '/wellness'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/meals'
    | '/_authenticated/onboarding'
    | '/_authenticated/plan'
    | '/_authenticated/recipe'
    | '/_authenticated/water'
    | '/_authenticated/wellness'
    | '/_authenticated/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wellness': {
      id: '/_authenticated/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AuthenticatedWellnessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/water': {
      id: '/_authenticated/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof AuthenticatedWaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipe': {
      id: '/_authenticated/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof AuthenticatedRecipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals': {
      id: '/_authenticated/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthenticatedMealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMealsRoute: typeof AuthenticatedMealsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedRecipeRoute: typeof AuthenticatedRecipeRoute
  AuthenticatedWaterRoute: typeof AuthenticatedWaterRoute
  AuthenticatedWellnessRoute: typeof AuthenticatedWellnessRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMealsRoute: AuthenticatedMealsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedRecipeRoute: AuthenticatedRecipeRoute,
  AuthenticatedWaterRoute: AuthenticatedWaterRoute,
  AuthenticatedWellnessRoute: AuthenticatedWellnessRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
